set(SRC_DIR ${CMAKE_ARGV3})
set(PATCH_FILE ${CMAKE_ARGV4})

file(READ ${PATCH_FILE} PATCH_FILE_CONTENTS)

string(JSON NUM_FILES_TO_PATCH LENGTH "${PATCH_FILE_CONTENTS}")
math(EXPR FILES_ARRAY_RANGE "${NUM_FILES_TO_PATCH}-1")

foreach(FILE_IDX RANGE ${FILES_ARRAY_RANGE})
	string(JSON FILENAME GET ${PATCH_FILE_CONTENTS} ${FILE_IDX} filename)
	string(JSON PATCHES  GET ${PATCH_FILE_CONTENTS} ${FILE_IDX} patches)

	file(READ "${SRC_DIR}/${FILENAME}" FILE_CONTENTS)

	string(JSON NUM_PATCHES LENGTH "${PATCHES}")
	math(EXPR PATCHES_ARRAY_RANGE "${NUM_PATCHES}-1")

	foreach(PATCH_IDX RANGE ${PATCHES_ARRAY_RANGE})
		string(JSON MATCH_STRING GET ${PATCHES} ${PATCH_IDX} match_string)
		string(JSON REPLACE_STRING GET ${PATCHES} ${PATCH_IDX} replace_string)

		string(REPLACE "${MATCH_STRING}" "${REPLACE_STRING}" FILE_CONTENTS "${FILE_CONTENTS}")
	endforeach()

	file(WRITE "${SRC_DIR}/${FILENAME}" "${FILE_CONTENTS}")
endforeach()
